### ISSUE TITLE
New release date

### ISSUE THREAD

**Issue by stefanDeveloper** [kfrancikowski/react-multiselect-dropdown-bootstrap#7]
Is there a plan to update the NPM version with the new typescript support?
Moreover, do you need support? I'd like to support this library and push it forward.

Best regards
Stefan

**Comment by kfrancikowski** [comment]
Hey, I've just released an update in NPM, but to be honest - i've lost control over this code after you've made a migration to typescript. I can see that there is a lot things to fix but I don't know how, because I don't have any experience with Typescript. For example: 
-a button to check/uncheck all options is gone
-parameter handleOnChange is not working anymore, but documentation says different. I can see in code that it's called now onChange, not sure why
-default values like "Nothing selected" text are gone

I'm a backend developer and this package is my creation after just one month practice with js and react and I feel that current version is not readable to me anymore. I'm a newbie in frontend and I would like to upkeep this package with my own speed, so I'm thinking about making a rollback to old version (without typescript), fix all reported bugs and expand this library later. 

I assume that you would like to keep the current version for your own projects so please do a fork or any other type of copy of this project and continue to work on it whathever you like :) It's obvious that you're far more advanced in JS than I and I cannot keep up with these changes. On the other hand I would like to keep this project and learn React more by supporting it in future, but with my own speed :)

**Comment by stefanDeveloper** [comment]
Hey, I’m sad to hear that there are some bugs. I thought I’ve tested it severely. Anyhow, I guess those aren’t hard to fix from my point of view.

However you like. Then I will do a fork. :)
